
# name: Deploy

# on:
#   push:
#     branches:
#     - master


# jobs:
#   build:
#     runs-on: macos-latest
#     steps:

#       - uses: actions/checkout@v1

#       - name: Dump file
#         run: ls -R

#       - name: Select Xcode
#         run: sudo xcode-select -switch /Applications/Xcode_11.3.app


#       - name: Xcode Version
#         run: /usr/bin/xcodebuild -version


#       - name: Build archive
#         run: |
#           xcodebuild -sdk iphoneos -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj \
#             -configuration Release -scheme CocoaHeadsNL \
#             -derivedDataPath DerivedData \
#             -archivePath DerivedData/Archive/CocoaHeadsNL archive


#       - name: Export Archive
#         run: |
#           xcodebuild -exportArchive \
#             -archivePath DerivedData/Archive/CocoaHeadsNL.xcarchive \
#             -export0ptionsPlist provisioning/App-Store.plist \
#             -exportPath DerivedData/ipa
name: Build and deploy Node.js

on: [push]

env:
  AZURE_WEBAPP_NAME: FaultCodeMgt-Mobile
  AZURE_WEBAPP_PACKAGE_PATH: './ios'

jobs:
  build_and_deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build
        run: |
          npm install
          npm i @capacitor/ios --force
          npx cap add ios

      - name: Upload artifact Admin
        uses: actions/upload-artifact@v2
        with:
          name: ios_build
          path: ${{env.AZURE_WEBAPP_ADMIN_PATH}}


      # - name: 'Deploy to Azure WebApp'
      #   uses: azure/webapps-deploy@v1
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_TOKENS }}
      #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

