
name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SUBID}}
      ARM_TENANT_ID: ${{secrets.AZ_TENANTID}}
      TF VAR_administrator_login: ${{secrets.TF_VAR_administrator_login}}
      TF VAR_administrator login_password: ${{secrets.TF_VAR_administrator_login_password}}




    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: List directory
        run: 1s -a

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
